### ISSUE TITLE
Faile to export the gltf file accordingly

### ISSUE THREAD

**Issue by elliotthwang** [ux3d/2gltf2#1]
C:\Users\AI>2gltf2.bat D:\V.ply

file = open(export_settings['gltf_filepath'], "wb")
OSError: [Errno 22] Invalid argument: 'C:\\Users\\AI/D:\\V.glb'

**Comment by UX3D-nopper** [comment]
Fixed here: https://github.com/ux3d/2gltf2/commit/35e7670ebec4c19373022fbe53a839beabe1113f
Please update to latest Blender 2.93.0 as well if using Windows.

**Comment by elliotthwang** [comment]
Thank you very much!
