### ISSUE TITLE
Failed to export the gltf file

### ISSUE THREAD

**Issue by elliotthwang** [ux3d/2gltf2#2]
C:\Users\AI>2gltf2.bat D:\V.ply

file = open(export_settings['gltf_filepath'], "wb")
OSError: [Errno 22] Invalid argument: 'C:\\Users\\AI/D:\\V.glb'

**Comment by UX3D-nopper** [comment]
https://github.com/ux3d/2gltf2/issues/1

**Comment by UX3D-nopper** [comment]
Duplicate.
