### ISSUE TITLE
can't operate the shell in linux based OS

### ISSUE THREAD

**Issue by yaryaraldebaran** [ux3d/2gltf2#4]
I've tried to execute the shell in my linux terminal but it doesn't access the blender and execute the python script. instead, it shows only this message
![image](https://user-images.githubusercontent.com/44632064/138203289-2bc709a1-8f17-4fde-b923-cf06801b40e3.png)

**Comment by UX3D-nopper** [comment]
You can only pass one argument, otherwise the script stops.
Try to execute `./2gltf2.sh ./Fairling.ply` The outputname is automatically generated.
